name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  NODE_VERSION: 16.x
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v2.1.5
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install --force
      - name: Build
        run: |
          npm run build

      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifacts
          path: |
            ./build/

          retention-days: 1
